config/routes.rb
Rails.application.routes.draw do

  resources :badges
  get 'contact', to: "contact#index"
  post 'contact', to: "contact#mail"

  post '/rate' => 'rater#create', :as => 'rate'
  resources :requests do
    member do
      post :accept
      post :reject
    end
  end
  resources :products
  root 'products#index'
  get 'pages/selldash'
  get 'pages/accepted'
  get 'pages/admindash'
  resources :conversations do
    resources :messages
 end

  # :controllers allocates custom made registration to devise
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users do
    member do
      resources :reviews
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :product

  def accept
    self.approved = true
    save
  end

  def reject
    self.approved = false
    save
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  def accept
    @request = Request.find(params[:id])
    @request.accept
    @request.product.purchased = true
    @request.product.save
    redirect_to pages_accepted_path(sender_id: current_user.id, recipient_id: @request.user.id)
  end

  def reject
    @request = Request.find(params[:id])
    @request.reject
    @request.destroy
    redirect_to pages_selldash_path
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.user_id = current_user.id

    respond_to do |format|
      if @request.save
        format.html { redirect_to products_path, notice: 'Request was successfully made.' }
        format.json { render :show, status: :created, location: products_path }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    authorize @request
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:user_id, :product_id, :approved, :message)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(request) do |f| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <% if params[:product_id].present? %>
      <%= f.hidden_field :product_id, value: params[:product_id] %>
    <% end %>
  </div>
  <br>

  <div class="field">
    <i class="material-icons prefix">mode_edit</i>
    <%= f.label 'Message' %>
    <%= f.text_area :message, :class => "materialize-textarea"%>
  </div>

  <div class="actions">
    <%= f.submit 'Send Request', :class => "waves-effect waves-light btn" %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th>Approved</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.user %></td>
        <td><%= request.product %></td>
        <td><%= request.approved %></td>
        <td><%= request.message %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<div class= "empty-space container">
  <br>
  <h4>Want this hamper?</h4>
  <h5>Send a friendly request message below <i class= "material-icons icon-size-md">mood</i></h5>
  <%= render 'form', request: @request %>
</div>
<div class= "login-top">
</div>

app/views/requests/show.html.erb
<div class= "container">
  <p id="notice"><%= notice %></p>

  <div class= "row">
    <div class= "col s4">
      <img src="<%= @request.user.avatar.url %>" alt="" class="circle responsive-img">
    </div>
    <div class= "col s8">
      <p><%= link_to @request.user.username, @request.user %> <%= rating_for @request.user, 'buying', { readonly: true}%></p>
      <p class= "bold request-message">"<%= @request.message %>"</p>
    </div>
  </div>


  <div class="row">
    <div class="col s12 m7">
      <div class="card">
        <div class="card-image">
          <img class= "resize-img" src="<%= @request.product.images[0].url %>">
        </div>
        <div class="card-content">
          <p><%= @request.product.title %></p>
          <p><%= @request.product.contents %></p>
        </div>
      </div>
    </div>
  </div>

  <% if correct_request?(@request)%>
  <div class= "row">
    <div class= "col s6">
      <%= link_to "Accept Request", accept_request_path(@request), method: :post, :class => "waves-effect waves-light btn" %>
    </div>
    <div class= "col s6">
      <%= link_to "Reject Request", reject_request_path(@request), method: :post, :class => "waves-effect waves-light btn" %>
    </div>
  </div>
  <% else %>
  <% end %>
</div>