config/routes.rb
Rails.application.routes.draw do

  resources :badges
  get 'contact', to: "contact#index"
  post 'contact', to: "contact#mail"

  post '/rate' => 'rater#create', :as => 'rate'
  resources :requests do
    member do
      post :accept
      post :reject
    end
  end
  resources :products
  root 'products#index'
  get 'pages/selldash'
  get 'pages/accepted'
  get 'pages/admindash'
  resources :conversations do
    resources :messages
 end

  # :controllers allocates custom made registration to devise
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users do
    member do
      resources :reviews
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :requests

  validates :title, presence: true
  validates :collection, presence: true
  validates :items, presence: true
  validates :contents, presence: true
  validates :description, presence: true
  validates :cost, presence: true, :numericality => {:only_integer => true}

  geocoded_by :location
  after_validation :geocode

  mount_uploaders :images, ProductUploader
  serialize :images, JSON

  def self.search(search)
    # where("title contents LIKE ? OR contents LIKE ?", "%#{search}%", "%#{search}%")
    where("contents LIKE ?", "%#{search}%")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
   # GET /index?order=[created_at, cost, contents]
  def index

    @products = Product.all.order(created_at: :desc).page(params[:page]).per_page(5)
    # Search function
    if params[:search]
      @products = Product.search(params[:search]).order("created_at DESC").page(params[:page]).per_page(5)
    else
      @products = Product.all.order(created_at: :desc).page(params[:page]).per_page(5)
    end

    # Ordering stuff by what's in params
    if params[:order] == 'created_at'
        @products = Product.all.order('created_at DESC').page(params[:page]).per_page(5)
    elsif params[:order] == 'cost'
        @products = Product.all.order('cost ASC').page(params[:page]).per_page(5)
    elsif params[:order] == 'contents'
        @products = Product.all.order('contents').page(params[:page]).per_page(5)
    else
    end

    # Google maps marker function
    @hash = Gmaps4rails.build_markers(@products) do |product, marker|
      marker.lat product.latitude
      marker.lng product.longitude
      marker.infowindow product.title
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    @product.location = current_user.location

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end

    if current_user.products.count == 5 && current_user.badges(name: "Super Producer").blank?
      Badge.create(user_id: current_user.id, name: "Super Producer")
    end

    if current_user.products.where(perishables: true).count == 5 && current_user.badges(name: "Green Thumb").blank?
      Badge.create(user_id: current_user.id, name: "Green Thumb")
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    authorize @product
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    authorize @product
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :user_id, :cost, :collection, :items, :contents, :perishables, :non_perishables, :description, {images: []})
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div>
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :cost %>
    <%= f.text_field :cost %>
  </div>

  <div class="field">
    <%= f.select :collection, options_for_select([["Select One", ""], "Delivery", "Pickup", "Delivery or Pickup"]), class: 'browser-default' %>
  </div>

  <div class="field">
    <%= f.label :items %>
    <%= f.number_field :items %>
  </div>

  <div class="field">
    <%= f.label :contents %>
    <%= f.text_area :contents, :class => "materialize-textarea" %>
  </div>

  <div class="field">
    <%= f.check_box :perishables %>
    <%= f.label :perishables %>
  </div>

  <div class="field">
    <%= f.check_box :non_perishables %>
    <%= f.label :non_perishables %>
  </div>
  <br>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :class => "materialize-textarea" %>
  </div>

  <div class="field">
    <%= f.label :images %>
    <br>
    <%= f.file_field :images, multiple: true %>
  </div>
  <br>

  <div class="actions">
    <%= f.submit 'Create', :class => "waves-effect waves-light btn" %>
  </div>
<% end %>
</div>

app/views/products/edit.html.erb
<div class= "empty-space container">
  <br>
  <div class= "card new-hamp">
    <h5>Edit your hamper</h5>
    <br>
  <%= render 'form', product: @product %>
  </div>
</div>
<div class= "login-top2">
</div>

app/views/products/index.html.erb
<div class= "product-all">
  <div class = "top-background">
    <div class ="container">
      <div class= "row">
        <div class= "col s12">
          <p id="notice"><%= notice %></p>
          <div class= "card intro-card">
            <p>Welcome to <span class= "bold">Hamper!</span></p>
            <i class= "material-icons icon-size-md">person</i>
            <i class= "material-icons icon-size-sm">pages</i>
            <i class= "material-icons icon-size-md">compare_arrows</i>
            <i class= "material-icons icon-size-sm">local_atm</i>
            <i class= "material-icons icon-size-md">person</i>
            <p>Buy and sell cheap hampers packed with extra pantry items or veggies!</p>
          </div>
        </div> <!-- col end  -->
      </div> <!-- row end  -->
    </div>
  </div>
  <div class = "container">
    <%= form_tag products_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil, :class => "btn waves-effect waves-light" %>
      </p>
    <% end %>
    <br>

    <!-- Sorts by filters. passes in order: string as params that activates if statements in controller  -->
    <!-- Dropdown Trigger -->
    <a class='dropdown-button btn' href='#' data-activates='dropdown1'>Sort by</a>
    <!-- Dropdown Structure -->
    <ul id='dropdown1' class='dropdown-content'>
      <li><%= link_to "Created at", products_path(order: 'created_at'), 'data-no-turbolink' => true %></li>
      <li><%= link_to "Cost", products_path(order: 'cost'), 'data-no-turbolink' => true %></li>
      <li><%= link_to "Content", products_path(order: 'contents'), 'data-no-turbolink' => true %></li>
    </ul>
    <br>
  </div>
  <br>

  <div class= "flex-container">
      <% @products.each do |product| %>
        <% if product.purchased == false%>
          <div class="row">
            <div class="col s12 m7">
              <div class="card card-width">
                <div class= "card-content">
                  <div class= "row">
                    <div class= "col s3">
                      <img src="<%= product.user.avatar.url %>" alt="" class="circle responsive-img">
                    </div>
                    <div class= "col s6">
                      <p><%= product.title %></p>
                      <p><%= link_to product.user.username, product.user %> <%= rating_for product.user, 'selling', { readonly: true}%></p>
                    </div>
                    <div class= "col s3">
                      <p><%= number_to_currency(product.cost) %></p>
                    </div>
                  </div>
                </div>
                <div class="card-image">
                  <img class= "resize-img" src="<%= product.images[0].url %>">
                </div>
                <div class="card-content">
                  <p><%= product.contents %></p>
                </div>
                <div class="card-action">
                  <p><%= link_to 'View', product %> <%= product.user.location %> </p>
                </div>
              </div>
            </div>
          </div>
          <% else %>
        <% end %>
      <% end %>
    <%= will_paginate @products %>
    <br>
  </div>
    <!-- Google Maps Display -->
    <div>
      <div id="map" style='height: 400px;'></div>
    </div>

    <script type='text/javascript'>
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    </script>
</div>

app/views/products/new.html.erb
<div class= "empty-space container">
  <br>
  <div class= "card new-hamp">
    <h5>Create new Hamper</h5>
    <br>
  <%= render 'form', product: @product %>
  </div>
</div>
<div class= "login-top2">
</div>

app/views/products/show.html.erb
<div class = "top-background">
  <div class="carousel carousel-slider" data-indicators="true">
    <% @product.images.each do |image| %>
      <a class="carousel-item" href="#one!"><img class= "resize-img" src="<%= image.url %>"></a>
    <% end %>
  </div>
</div>

<div class = "container">
  <p id="notice"><%= notice %></p>
  <div class= "row">
    <div class= "col s6">
      <h4><%= @product.title %></h4>
    </div>
    <div class= "col s3">
      <% if correct_user?(@product.user) %>
        <%= link_to 'Edit', edit_product_path(@product), :class => "waves-effect waves-light btn" %>
        <br>
        <%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' }, :class => "waves-effect waves-light btn" %>
      <% else %>
      <% end %>
    </div>
    <div class= "col s3">
      <% if correct_user?(@product.user) && @product.created_at < 5.hours.ago %>
        <%= link_to 'Give', edit_product_path(@product), :class => "waves-effect waves-purple btn" %>
      <% else %>
      <% end %>
    </div>
  </div>
  <div class= " card row">
    <div class = "col s6">
      <p> <i class= "material-icons">person</i> <%= link_to @product.user.username, @product.user %> </p>
      <p> <i class= "material-icons">hourglass_full</i> <%= @product.created_at %> </p>
      <p> <i class= "material-icons">local_offer</i> <%= number_to_currency(@product.cost) %> </p>
      <p> <i class= "material-icons">place</i> <%= @product.user.location %> </p>
    </div>
    <div class = "col s6">
      <p> <i class= "material-icons">shopping_cart</i> <%= @product.collection %> </p>
      <p> <i class= "material-icons">restaurant</i> Perishables: <%= @product.perishables %> </p>
      <p> <i class= "material-icons">restaurant_menu</i> Non-Perishables: <%= @product.non_perishables %> </p>
      <p> <i class= "material-icons">shopping_basket</i> Quantity: <%= @product.items %> </p>
    </div>
  </div>

  <div class = "row">
    <div class= "col s12">
      <h5>Contents</h5>
      <%= @product.contents %>
      <h5>Description</h5>
      <%= @product.description %>
    </div>
  </div>

<% if correct_user?(@product.user) %>
<% else %>
  <div class= "row">
    <div class= "col s6">
    <%= link_to "Request Hamper", new_request_path(product_id: @product.id), :class => "waves-effect waves-light btn"%>
    </div>
  </div>
<% end %>
</div>